apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldapper
  name: postgresqldapper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresqldapper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresqldapper
    spec:
      imagePullSecrets:
        - name: ibmcloudcred
      containers:
      - env:
        - name: ConnectionString
          value: ' User ID=postgres;Password=secret1234;Host=postgresdata;Port=5432;Database=postgres;'
        image: arck8scr.azurecr.io/postgresqldapper:latest
        imagePullPolicy: ""
        name: postgresqldapper
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        ports:
        - containerPort: 5001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldapper
  name: postgresqldapper
spec:
  type: LoadBalancer
  ports:
  - name: "5010"
    port: 5010
    targetPort: 5001
  selector:
    io.kompose.service: postgresqldapper
status:
  loadBalancer: {}

