version: '3.4'

services:
  apigateway:
    image: apigateway:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "APIGateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_apigateway$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\APIGateway:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_apigateway$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_apigateway$ \"/app/bin/Debug/netcoreapp3.1/APIGateway.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  doctorservice:
    image: doctorservice:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DoctorService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_doctorservice$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\DoctorService:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_doctorservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_doctorservice$ \"/app/bin/Debug/netcoreapp3.1/DoctorService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  loginfunctionality:
    image: loginfunctionality:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "LoginFunctionality"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_loginfunctionality$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\LoginFunctionality:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_loginfunctionality$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_loginfunctionality$ \"/app/bin/Debug/netcoreapp3.1/LoginFunctionality.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  loginservicedapr:
    image: loginservicedapr:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "LoginServiceDapr"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_loginservicedapr$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\LoginServiceDapr:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_loginservicedapr$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_loginservicedapr$ \"/app/bin/Debug/netcoreapp3.1/LoginServiceDapr.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  patientservice:
    image: patientservice:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "PatientService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_patientservice$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\PatientService:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_patientservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_patientservice$ \"/app/bin/Debug/netcoreapp3.1/PatientService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  postgresqldapper:
    image: postgresqldapper:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "PostGresqlDapper"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_postgresqldapper$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\PostGresqlDapper:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_postgresqldapper$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_postgresqldapper$ \"/app/bin/Debug/netcoreapp3.1/PostGresqlDapper.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  productservice:
    image: productservice:dev
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ProductService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_productservice$
    volumes:
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker\ProductService:/app
      - C:\Users\SormitaChakraborty\source\repos\PostGresqlDapperLoginDocker:/src
      - C:\Users\SormitaChakraborty\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_productservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_productservice$ \"/app/bin/Debug/netcoreapp3.1/ProductService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
